# Generated by Django 3.2.15 on 2022-10-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usu_rut', models.CharField(max_length=150)),
                ('usu_Password', models.CharField(max_length=500)),
                ('usu_nombre', models.CharField(default='None', max_length=500, null=True)),
                ('usu_rol', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pedido_fecha', models.DateField()),
                ('pedido_direccion', models.CharField(max_length=500)),
                ('pedido_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('fruta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fruta_nombre', models.CharField(max_length=500)),
                ('fruta_cantidad', models.IntegerField(default=False)),
                ('fruta_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido')),
            ],
        ),
    ]
