# Generated by Django 3.2.15 on 2022-10-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usu_Password',
            new_name='usu_password',
        ),
    ]
