# Generated by Django 3.2.15 on 2022-10-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0002_rename_usu_password_usuario_usu_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_estado',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_apellidom',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_apellidop',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_email',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usu_telefono',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fruta',
            name='fruta_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_nombre',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_rut',
            field=models.CharField(max_length=100),
        ),
    ]
