# Generated by Django 3.2.15 on 2022-10-12 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0003_auto_20221011_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='fruta_precio',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Ofertaproductor',
            fields=[
                ('oferta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oferta_estado', models.CharField(default='None', max_length=100, null=True)),
                ('oferta_fecha', models.DateField()),
                ('oferta_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido')),
                ('oferta_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('carro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carro_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='fruta',
            name='fruta_carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.carro'),
        ),
        migrations.AddField(
            model_name='fruta',
            name='fruta_ofertaproductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.ofertaproductor'),
        ),
    ]
