# Generated by Django 3.2.15 on 2022-10-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0004_auto_20221012_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(default=False)),
                ('nombres', models.CharField(default=False, max_length=100)),
                ('apellido_p', models.CharField(default=False, max_length=100)),
                ('apellido_m', models.CharField(default=False, max_length=100)),
                ('cargo', models.CharField(default=False, max_length=100)),
                ('sueldo', models.IntegerField(default=False)),
                ('fecha_i', models.DateField()),
                ('fecha_t', models.DateField()),
            ],
        ),
    ]
