# Generated by Django 3.2.15 on 2022-10-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0005_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktienda',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_nombre_fruta', models.CharField(max_length=100)),
                ('stock_cantidad', models.IntegerField(default=False)),
                ('stock_precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido')),
            ],
        ),
    ]
