# Generated by Django 3.2.15 on 2022-10-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0007_auto_20221014_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktienda',
            name='stock_cantidad',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stocktienda',
            name='stock_precio',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
