# Generated by Django 3.2.15 on 2022-10-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0009_auto_20221025_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('venta_tamano', models.IntegerField(default=False, null=True)),
                ('venta_capacidad_carga', models.IntegerField(default=False, null=True)),
                ('venta_refrigeracion', models.CharField(default=False, max_length=100, null=True)),
                ('venta_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.pedido')),
            ],
        ),
    ]
