# Generated by Django 3.2.15 on 2022-10-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0010_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subastatransportista',
            fields=[
                ('subasta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subasta_valor', models.IntegerField(default=False, null=True)),
                ('subasta_estado', models.CharField(default=False, max_length=100, null=True)),
                ('subasta_transportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.usuario')),
                ('subasta_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.venta')),
            ],
        ),
    ]
