# Generated by Django 3.2.15 on 2022-11-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0011_subastatransportista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruta',
            name='fruta_ofertaproductor',
        ),
        migrations.RemoveField(
            model_name='ofertaproductor',
            name='oferta_pedido',
        ),
        migrations.AddField(
            model_name='ofertaproductor',
            name='oferta_fruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.fruta'),
        ),
    ]
