# Generated by Django 3.2.15 on 2022-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0012_auto_20221101_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproductor',
            name='oferta_monto',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
