# Generated by Django 3.2.15 on 2022-11-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0013_ofertaproductor_oferta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaproductor',
            name='oferta_fecha',
            field=models.DateField(null=True),
        ),
    ]
