# Generated by Django 3.2.15 on 2022-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0015_alter_ofertaproductor_oferta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_estado',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Venta_interna',
            fields=[
                ('venta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('venta_estado', models.IntegerField(default=False, null=True)),
                ('venta_carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.carro')),
            ],
        ),
    ]
