# Generated by Django 3.2.15 on 2022-11-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0016_auto_20221114_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_interna',
            name='venta_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='venta_interna',
            name='venta_monto',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
