# Generated by Django 3.2.15 on 2022-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0017_auto_20221114_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('peticion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peticion_nombre', models.CharField(default=False, max_length=100, null=True)),
                ('peticion_telefono', models.CharField(default=False, max_length=100, null=True)),
                ('peticion_descripcion', models.CharField(default=False, max_length=600, null=True)),
            ],
        ),
    ]
