# Generated by Django 3.2.15 on 2022-11-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0018_peticion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='contrato_ape_m',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contrato_ape_p',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contrato_cargo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contrato_nombres',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='contrato_rut',
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frutas.usuario'),
        ),
    ]
