# Generated by Django 3.2.15 on 2022-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutas', '0019_auto_20221121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproductor',
            name='oferta_cantidad',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
